import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Survey from "../components/survey/Survey";
import ProgressProvider from "../components/contexts/ProgressProvider";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProgressProvider>
        <Survey></Survey>
      </ProgressProvider>
    </div>
  );
};

export default Home;
