import type { NextPage } from "next";
import Head from "next/head";
import Survey from "../components/survey/Survey";
import ProgressProvider from "../components/contexts/ProgressProvider";
import packageJson from "../package.json";
import DetailsProvider from "../components/contexts/DetailsProvider";
import Image from "next/image";
const Home: NextPage = () => {
  return (
    <div style={{ marginLeft: "5vw", marginRight: "5vw" }}>
      <Head>
        <title>C-B Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          position: "absolute",
          left: "4vw",
          top: "2vh",
          padding: "1em",
          border: "2px dotted black",
          borderRadius: "64px",
        }}
      >
        {packageJson.version}a
      </div>
      <Image
        src={"/c-b.png"}
        width="100%"
        height="50vh"
        layout="responsive"
        objectPosition={"block"}
        objectFit="cover"
        style={{ zIndex: -1, opacity: 0.3 }}
        alt="cost-benefit analysis background"
      ></Image>
      <ProgressProvider>
        <DetailsProvider>
          <Survey></Survey>
        </DetailsProvider>
      </ProgressProvider>
    </div>
  );
};

export default Home;
