import type { NextPage } from "next";
import Head from "next/head";
import Survey from "../components/survey/Survey";

import DetailsProvider from "../components/contexts/DetailsProvider";

import Footer from "../components/survey/Footer";
const Home: NextPage = () => {
  return (
    <div style={{ marginLeft: "5vw", marginRight: "5vw" }}>
      <Head>
        <title>C-B Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DetailsProvider>
        <Survey></Survey>
      </DetailsProvider>

      <Footer></Footer>
    </div>
  );
};

export default Home;
